swagger: '2.0'
info:
  title: WSO2 Identity Server OAuth2 resource Registration Endpoint
  description: >-
    This document specifies a **OAuth2 Resource Registration Endpoint** for WSO2
    **Identity Server** .
  version: '1.0.0 It is written with [swagger 2](http://swagger.io/).'
  contact:
    name: WSO2
    url: 'http://wso2.com/identity-and-access-management'
    email: architecture@wso2.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
schemes:
  - https
host: localhost
basePath: /api/identity/oauth2/resourcev1.0
consumes:
  - application/json
produces:
  - application/json
paths:
  /ResourceRegistration/resource:
    post:
      tags:
        - Resource
      summary: Add a resource
      description: This method uses to register resources in Authorization server.
      operationId: registerResource
      parameters:
        - in: body
          name: resource
          description: >-
            The resource description which resource owner save in Authorization
            server.
          schema:
            $ref: '#/definitions/ResourceDetails'
      responses:
        '201':
          description: |
            Resource registered successfully.
          schema:
            $ref: '#/definitions/createResource'
        '400':
          description: Invalid input.
          schema:
            $ref: '#/definitions/error'
definitions:
  createResource:
    properties:
      resourceId:
        type: string
        description: ' Returning resource Id after successfull registration.'
        example: |
          0f77c1f2-64c3-452d-b622-4519b6906949
      policy_uri:
        type: string
        description: ' Policy_URI used for user access'
        example: 'http://as.example.com/rs/222/resource/KX3A-39WE/policy'
  ResourceDetails:
    type: object
    required:
      - resource_scopes
      - icon_uri
      - name
      - type
      - description
    properties:
      resource_scopes:
        type: array
        example:
          - view
          - 'http://photoz.example.com/dev/actions/print'
        description: |
          An array of strings indicating the available scopes for this resource.
        items:
          type: string
      icon_uri:
        type: string
        description: |
          A URI for a graphic icon representing the resource.  
        example: 'http://www.example.com/icons/sky.png'
      name:
        type: string
        example: Resource description sample
        description: >
          A human-readable string describing a resource of one or more
          resources.The authorization server MAY use the name in any user
          interface it presents to the resource owner.
      type:
        type: string
        example: 'http://www.example.com/rs/photoalbum'
        description: |
          A string uniquely identifying the semantics of the resource.
      description:
        type: string
        example: Print out and produce PDF files of photo
        description: >
          A human-readable string describing the resource at length. The
          authorization server MAY use this description in any user interface it
          presents to a resource owner, for example, for resource protection
          monitoring or policy setting.
  error:
    type: object
    properties:
      error:
        type: string
      error_description:
        type: string
parameters:
  resourceId:
    name: resourceId
    in: path
    description: ID ofthe  resource
    required: true
    type: string
